<?php
print $this->showMessages();

$adr = "/img/lg/nophoto.png";

$form = $this->form;
$form->setAttribute('action', $this->url('cart', array('action' => 'add')));
$form->prepare();
?>
<div class="row">
    <div class="col-xs-4">
        <div class="fluid_container">
            <div class="camera_wrap camera_magenta_skin" id="camera_wrap">
                <?php if (count($product['pictures']) == 0) :?>
                    <div data-thumb="<?=$adr?>" data-src="<?=$adr?>"></div>
                <?php else:
                    foreach($product['pictures'] as $pict) :
                        $adr =  "/img/lg/".$pict;
                        $thumb = "/img/thumbs/".$pict;?>
                        <div data-thumb="<?=$thumb?>" data-src="<?=$adr?>" data-alignment="center"></div>
                    <?php endforeach;
                endif;?>
            </div>
        </div>
    </div>
    <div class="col-xs-8">
        <div class="row">
            <h1><?=$product['name'];?></h1>
        </div>
        <div class="row">
            <h3>Цена: <?=$product['price'];?> грн.</h3>
            <?php
            if ($product['inCart']){
                echo '<button class="btn btn-default" disabled>Уже в корзине</button>';
            } else {
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('security'));
                echo $this->formHidden($form->get('goods')->setAttribute('value', $product['id']));
                echo $this->formHidden($form->get('amount')->setAttribute('value', 1));
                echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
                echo $this->form()->closeTag();
            }
            ?>
        </div>
        <div class="row">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#descr" aria-controls="descr" role="tab" data-toggle="tab">Описание</a></li>
                <li role="presentation"><a href="#prop" aria-controls="prop" role="tab" data-toggle="tab">Характеристики</a></li>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="descr"><p><?=$product['descr'];?></p></div>
                <div role="tabpanel" class="tab-pane" id="prop">
                    <dl class="dl-horizontal">
                        <?php
                        foreach($product['properties'] as $name => $value) {
                            echo "<p><dt>$name</dt><dd>$value</dd></p>";
                        }?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">

</div>
