<?php if ($this->pageCount): ?>
    <div>
        <ul class="pagination">

            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?=$this->url($this->route)."?page=".$this->previous;?>">&laquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">&laquo;</a>
                </li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?=$this->url($this->route)."?page=".$page;?>">
                            <?=$page;?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?=$page;?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?=$this->url($this->route)."?page=".$this->next; ?>">&raquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">&raquo;</a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>