<?php
print $this->showMessages();
$cost = 0;
?>
<div class="row">
    <div class="col-sm-10 col-md-offset-1">
        <h2>Корзина</h2>
        <div class="table-responsive">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Название продукта</th>
                        <th>Колличество</th>
                        <th>Цена</th></th>
                        <th></th>
                    </tr>
                    <?php
                    foreach ($cartGoods as $goodsID => $product) :
                        $name = $product['name'];
                        $amount = $product['amount'];
                        $price = $product['price'];
                        $stock = $product['stock'];
                        $cost += $amount*$price;?>
                        <tr data-goods-id="<?=$goodsID?>">
                            <td class="name">
                                <img src="/img/thumbs/<?=$product['pict'];?>" alt="<?=$name;?>">
                                <b><a href="catalog/view/<?=$goodsID?>"><?=$name;?></a></b>
                            </td>
                            <td class="num">
                                <button type="button" class="btn btn-default btn-xs" data-sign="less">
                                    <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                                </button>
                                <input type="text" class="qty" value="<?=$amount;?>" data-stock-qty="<?=$stock?>" disabled>
                                <button type="button" class="btn btn-default btn-xs" data-sign="more">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </button>
                            </td>
                            <td><?=$price;?> грн.</td>
                            <td>
                                <button type="button" class="btn btn-default btn-xs" data-remove="true" title="Удалить">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </button>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    <tr>
                        <td colspan="2">Общая стоимость</td>
                        <td id="cost"><?=$cost?> грн.</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <button type="button" class="btn btn-success">Оформить заказ</button>
        </div>
    </div>
</div>
<script>
    $('button[data-sign]').on('click', function () {
        var $btn = $(this),
            goodsId = $btn.closest('tr').attr('data-goods-id'),
            sign = $btn.attr('data-sign'),
            qty = +$btn.siblings('input').attr('value'),
            stock = +$btn.siblings('input').attr('data-stock-qty'),
            product, posting,
            url = '/cart/update';

        if (sign == 'more' && qty < stock) {
            qty++;
        } else if (sign == 'less' && qty > 1) {
            qty--;
        }
        $btn.siblings('input').attr('value', qty);

        product = {id: goodsId, qty: qty};
        posting = $.post(url, product);

        $('button').attr('disabled',"disabled");

        posting.done(function(data) {
            $('button').removeAttr('disabled');
            updButtons();
            updCart(data);
        });
    });

    $('button[data-remove]').on('click', function () {
        var $btn = $(this),
            goodsId = $btn.closest('tr').attr('data-goods-id'),
            data, posting,
            url = '/cart/delete';

        data = {id: goodsId};
        posting = $.post(url, data);

        $('button').attr('disabled',"disabled");

        posting.done(function(data) {
            $('button').removeAttr('disabled');
            updButtons();
            var selector = "tr[data-goods-id="+goodsId+"]";
            $(selector).remove();
            updCart(data);
        });
    });

    function updButtons(){
        $('button[data-sign]').each(function() {
            var $btn = $(this),
                sign = $btn.attr('data-sign'),
                qty = +$btn.siblings('input').attr('value'),
                stock = +$btn.siblings('input').attr('data-stock-qty');
            if (sign == 'more' && qty == stock) {
                $btn.attr('disabled',"disabled");
            } else if (sign == 'less' && qty == 1) {
                $btn.attr('disabled',"disabled");
            }
        });
    }

    updButtons();

    $(function() {
        $( document ).tooltip();
    });    
</script>
